const cron = require('node-cron');
const nodemailer = require('nodemailer');
const User = require('../models/User');
const TimeEntry = require('../models/TimeEntry');

// Email transporter (uses environment explicitly)
const getTransporter = () => nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

// Run every Sunday at 23:59
cron.schedule('59 23 * * 0', async () => {
  console.log('Running weekly timesheet mailer...');

  try {
    // Generate dates representing the past 7 days up to now
    const endDate = new Date(); 
    const startDate = new Date();
    startDate.setDate(endDate.getDate() - 7);
    
    // Fetch all users
    const users = await User.find();
    const transporter = getTransporter();

    for (const user of users) {
      if (!user.isEmailVerified) continue; // Skip unverified users
      
      const entries = await TimeEntry.find({
        userId: user._id,
        date: { $gte: startDate, $lte: endDate }
      }).populate('projectId', 'name clientOrTask').sort({ date: 1 });

      if (entries.length === 0) {
        continue; // Skip silently if no entries logged
      }

      let tableRows = '';
      let totalMins = 0;
      let csvContent = 'Date,Project,Client,Sub Task,Hours,Notes\n';

      entries.forEach(entry => {
        const dateStr = new Date(entry.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        const projName = entry.projectId ? entry.projectId.name : 'Internal';
        const durationStr = `${Math.floor(entry.duration / 60)}:${(entry.duration % 60).toString().padStart(2, '0')}`;
        totalMins += entry.duration;

        const dateForCsv = new Date(entry.date).toISOString().split('T')[0];
        const clientName = entry.projectId?.clientOrTask || '';
        const hoursCsv = (entry.duration / 60).toFixed(2);
        const notesCsv = (entry.notes || '').replace(/"/g, '""').replace(/\n/g, ' | ');
        csvContent += `"${dateForCsv}","${projName}","${clientName}","${entry.taskType}",${hoursCsv},"${notesCsv}"\n`;

        tableRows += `
          <tr>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 14px;">${dateStr}</td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 14px;"><strong>${projName}</strong></td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 14px;">${entry.taskType}</td>
            <td style="padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 14px; font-weight: 600;">${durationStr}</td>
          </tr>
        `;
      });

      const totalFormatted = `${Math.floor(totalMins / 60)}:${(totalMins % 60).toString().padStart(2, '0')}`;

      const html = `
        <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; max-width: 640px; margin: 0 auto; color: #1e293b; background: white; padding: 20px;">
          <h2 style="color: #f36c21; font-weight: 800; font-size: 24px; margin-bottom: 8px;">Weekly Timesheet Summary</h2>
          <p style="font-size: 16px; margin-bottom: 24px; color: #475569;">Hello ${user.name}, here is a high-level summary of the time you logged over the past week.</p>
          
          <table style="width: 100%; border-collapse: collapse; text-align: left; margin-bottom: 24px;">
            <thead>
              <tr>
                <th style="padding: 12px 10px; background: #f8fafc; border-bottom: 2px solid #cbd5e1; font-size: 13px; text-transform: uppercase;">Date</th>
                <th style="padding: 12px 10px; background: #f8fafc; border-bottom: 2px solid #cbd5e1; font-size: 13px; text-transform: uppercase;">Project</th>
                <th style="padding: 12px 10px; background: #f8fafc; border-bottom: 2px solid #cbd5e1; font-size: 13px; text-transform: uppercase;">Task Activity</th>
                <th style="padding: 12px 10px; background: #f8fafc; border-bottom: 2px solid #cbd5e1; font-size: 13px; text-transform: uppercase;">Time Logged</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows}
            </tbody>
            <tfoot>
              <tr>
                <td colspan="3" style="padding: 16px 10px; font-weight: 800; text-align: right; font-size: 16px; color: #1e293b; border-bottom: 2px solid #f8fafc;">Total Hours:</td>
                <td style="padding: 16px 10px; font-weight: 800; font-size: 16px; color: #f36c21; border-bottom: 2px solid #f8fafc;">${totalFormatted}</td>
              </tr>
            </tfoot>
          </table>
          <p style="font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px;">This is an automated message generated by OnCloud Time Track.</p>
        </div>
      `;

      await transporter.sendMail({
        from: process.env.EMAIL_USER,
        to: user.email,
        subject: 'Your Weekly Timesheet Summary — OnCloud Time',
        html: html,
        attachments: [
          {
            filename: 'Weekly_Timesheet.csv',
            content: csvContent
          }
        ]
      });
    }

    console.log('Weekly timesheet mailer execution fully completed.');
  } catch (error) {
    console.error('Error running weekly timesheet mailer:', error);
  }
});
